export const profile = {
  mobile: {
    wrapper: {
      minHeight: "100vh",
      backgroundColor: "#f9fafb",
      padding: "1rem",
    },
    content: {
      maxWidth: "800px",
      margin: "0 auto",
    },
    card: {
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
      padding: "1.5rem",
    },
    title: {
      fontSize: "1.5rem",
      fontWeight: 700,
      color: "#1f2937",
      marginBottom: "1.5rem",
    },
    section: {
      marginBottom: "2rem",
      paddingBottom: "1.5rem",
      borderBottom: "1px solid #e5e7eb",
    },
    sectionTitle: {
      fontSize: "1.1rem",
      fontWeight: 600,
      color: "#374151",
      marginBottom: "1rem",
    },
    form: {
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
    },
    inputGroup: {
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
    },
    label: {
      fontSize: "0.875rem",
      fontWeight: 500,
      color: "#4b5563",
    },
    input: {
      padding: "0.75rem",
      border: "1px solid #d1d5db",
      borderRadius: "8px",
      fontSize: "1rem",
    },
    buttonGroup: {
      display: "flex",
      gap: "0.5rem",
      marginTop: "0.5rem",
    },
    primaryButton: {
      flex: 1,
      padding: "0.75rem",
      backgroundColor: "#1f2937",
      color: "#ffffff",
      border: "none",
      borderRadius: "8px",
      fontSize: "1rem",
      fontWeight: 500,
      cursor: "pointer",
    },
    secondaryButton: {
      flex: 1,
      padding: "0.75rem",
      backgroundColor: "transparent",
      color: "#1f2937",
      border: "1px solid #1f2937",
      borderRadius: "8px",
      fontSize: "1rem",
      fontWeight: 500,
      cursor: "pointer",
    },
    infoDisplay: {
      display: "flex",
      flexDirection: "column",
      gap: "0.75rem",
    },
    premiumBadge: {
      display: "inline-block",
      padding: "0.25rem 0.75rem",
      backgroundColor: "#fbbf24",
      color: "#78350f",
      borderRadius: "9999px",
      fontSize: "0.875rem",
      fontWeight: 600,
    },
    freeBadge: {
      display: "inline-block",
      padding: "0.25rem 0.75rem",
      backgroundColor: "#e5e7eb",
      color: "#374151",
      borderRadius: "9999px",
      fontSize: "0.875rem",
      fontWeight: 600,
    },
    quotaDisplay: {
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
    },
    quotaItem: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
    },
    quotaLabel: {
      fontSize: "0.875rem",
      color: "#6b7280",
    },
    quotaValue: {
      fontSize: "0.875rem",
      fontWeight: 600,
      color: "#1f2937",
    },
    progressBar: {
      width: "100%",
      height: "8px",
      backgroundColor: "#e5e7eb",
      borderRadius: "4px",
      overflow: "hidden",
    },
    progressFill: {
      height: "100%",
      backgroundColor: "#3b82f6",
      transition: "width 0.3s ease",
    },
    watermarkNote: {
      fontSize: "0.875rem",
      color: "#6b7280",
      fontStyle: "italic",
    },
    upgradeButton: {
      width: "100%",
      padding: "0.75rem",
      backgroundColor: "#10b981",
      color: "#ffffff",
      border: "none",
      borderRadius: "8px",
      fontSize: "1rem",
      fontWeight: 600,
      cursor: "pointer",
      marginTop: "0.5rem",
    },
    memoryList: {
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
    },
    memoryItem: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "1rem",
      backgroundColor: "#f9fafb",
      borderRadius: "8px",
    },
    memoryInfo: {
      flex: 1,
    },
    memoryTitle: {
      fontSize: "1rem",
      fontWeight: 600,
      color: "#1f2937",
      marginBottom: "0.25rem",
    },
    memoryMeta: {
      fontSize: "0.875rem",
      color: "#6b7280",
      marginBottom: "0.5rem",
    },
    statusBadge: {
      display: "inline-block",
      padding: "0.25rem 0.75rem",
      borderRadius: "9999px",
      fontSize: "0.75rem",
      fontWeight: 600,
      color: "#ffffff",
    },
    downloadButton: {
      padding: "0.5rem 1rem",
      backgroundColor: "#1f2937",
      color: "#ffffff",
      border: "none",
      borderRadius: "8px",
      fontSize: "0.875rem",
      fontWeight: 500,
      cursor: "pointer",
    },
    actionButtons: {
      display: "flex",
      gap: "0.5rem",
      flexWrap: "wrap" as const,
    },
    regenerateButton: {
      padding: "0.5rem 1rem",
      backgroundColor: "#8b5cf6",
      color: "#ffffff",
      border: "none",
      borderRadius: "8px",
      fontSize: "0.875rem",
      fontWeight: 500,
      cursor: "pointer",
    },
    deleteButton: {
      padding: "0.5rem 1rem",
      backgroundColor: "transparent",
      color: "#ef4444",
      border: "1px solid #ef4444",
      borderRadius: "8px",
      fontSize: "0.875rem",
      fontWeight: 500,
      cursor: "pointer",
    },
    footer: {
      marginTop: "2rem",
      paddingTop: "1.5rem",
      borderTop: "1px solid #e5e7eb",
      textAlign: "center" as const,
    },
    signOutButton: {
      padding: "0.75rem 2rem",
      backgroundColor: "transparent",
      color: "#ef4444",
      border: "1px solid #ef4444",
      borderRadius: "8px",
      fontSize: "1rem",
      fontWeight: 500,
      cursor: "pointer",
    },
    loading: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      minHeight: "100vh",
      fontSize: "1.125rem",
      color: "#6b7280",
    },
    error: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      minHeight: "100vh",
      fontSize: "1.125rem",
      color: "#ef4444",
    },
    emptyState: {
      textAlign: "center" as const,
      padding: "2rem",
      color: "#6b7280",
    },
  },
  desktop: {
    wrapper: {
      minHeight: "100vh",
      backgroundColor: "#f9fafb",
      padding: "2rem",
    },
    card: {
      padding: "2rem",
    },
    title: {
      fontSize: "2rem",
    },
  },
};