export const timeline = {
  mobile: {
    wrapper: {
      minHeight: "100vh",
      backgroundColor: "#f9fafb",
      padding: "1rem",
    },
    content: {
      maxWidth: "800px",
      margin: "0 auto",
    },
    card: {
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
      padding: "1.5rem",
    },
    title: {
      fontSize: "1.5rem",
      fontWeight: 700,
      color: "#1f2937",
      marginBottom: "0.5rem",
    },
    subtitle: {
      fontSize: "0.875rem",
      color: "#6b7280",
      marginTop: "0.5rem",
    },
    emptyState: {
      textAlign: "center" as const,
      padding: "2rem",
      color: "#6b7280",
    },
    loading: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      minHeight: "100vh",
      fontSize: "1.125rem",
      color: "#6b7280",
    },
    filterSection: {
      marginBottom: "2rem",
    },
    filterTitle: {
      fontSize: "1rem",
      fontWeight: 600,
      color: "#374151",
      marginBottom: "0.75rem",
    },
    filterButtons: {
      display: "flex",
      gap: "0.5rem",
      flexWrap: "wrap" as const,
    },
    filterButton: {
      padding: "0.5rem 1rem",
      backgroundColor: "transparent",
      color: "#1f2937",
      border: "1px solid #1f2937",
      borderRadius: "8px",
      fontSize: "0.875rem",
      fontWeight: 500,
      cursor: "pointer",
    },
    filterButtonActive: {
      padding: "0.5rem 1rem",
      backgroundColor: "#1f2937",
      color: "#ffffff",
      border: "1px solid #1f2937",
      borderRadius: "8px",
      fontSize: "0.875rem",
      fontWeight: 500,
      cursor: "pointer",
    },
    timelineContainer: {
      position: "relative" as const,
    },
    timelineLine: {
      position: "absolute",
      left: "2rem",
      top: 0,
      bottom: 0,
      width: "2px",
      backgroundColor: "#e5e7eb",
    },
    monthGroup: {
      marginBottom: "2rem",
    },
    monthHeader: {
      position: "relative" as const,
      marginBottom: "1rem",
      paddingLeft: "4rem",
    },
    monthDot: {
      position: "absolute",
      left: "1.5rem",
      top: "0.5rem",
      width: "1rem",
      height: "1rem",
      borderRadius: "50%",
      backgroundColor: "#3b82f6",
      border: "3px solid #ffffff",
      boxShadow: "0 0 0 2px #3b82f6",
    },
    monthTitle: {
      fontSize: "1.25rem",
      fontWeight: 600,
      color: "#1f2937",
      margin: 0,
    },
    memoryList: {
      marginLeft: "4rem",
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
    },
    memoryCard: {
      padding: "1rem",
      backgroundColor: "#f9fafb",
      borderRadius: "8px",
      border: "1px solid #e5e7eb",
      cursor: "pointer",
      transition: "transform 0.2s, box-shadow 0.2s",
    },
    memoryHeader: {
      display: "flex",
      alignItems: "center",
      gap: "0.75rem",
      marginBottom: "0.5rem",
    },
    moodEmoji: {
      fontSize: "1.5rem",
    },
    memoryInfo: {
      flex: 1,
    },
    memoryTitle: {
      fontSize: "1rem",
      fontWeight: 600,
      color: "#1f2937",
      margin: "0 0 0.25rem 0",
    },
    memoryDate: {
      fontSize: "0.875rem",
      color: "#6b7280",
      margin: 0,
    },
    statusBadge: {
      display: "inline-block",
      padding: "0.25rem 0.75rem",
      borderRadius: "9999px",
      fontSize: "0.75rem",
      fontWeight: 600,
      color: "#ffffff",
    },
    memoryThumbnail: {
      width: "100%",
      height: "120px",
      objectFit: "cover" as const,
      borderRadius: "8px",
      marginTop: "0.5rem",
    },
    backButton: {
      padding: "0.75rem 1.5rem",
      backgroundColor: "transparent",
      color: "#1f2937",
      border: "1px solid #1f2937",
      borderRadius: "8px",
      fontSize: "1rem",
      fontWeight: 500,
      cursor: "pointer",
    },
  },
  desktop: {
    wrapper: {
      padding: "2rem",
    },
    card: {
      padding: "2rem",
    },
    title: {
      fontSize: "2rem",
    },
  },
};